"""alter table todos

Revision ID: 63000396243f
Revises: d8f58e323d88
Create Date: 2024-01-08 01:43:29.143528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63000396243f'
down_revision = 'd8f58e323d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
